[package]
name = "CSS-colors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"
chrono = "0.4.19"
rug = "1.24.1"
rand="0.8.1"